    TempPtr00_lo = $00                          ; $00
    TempPtr02_lo = $02                          ; $02
    TempPtr08_lo = $08                          ; $08

	ObstaclePointerLo = $0A						; $0A
	
	Unknown10_CollisionAndScrollingTemp = $10	; $10
	
	Unknown13_Horizontal_32pixelUnitForObject = $13		; $13
	Unknown14_Horizontal_256pixelUnitForObject = $14	; $14

    MainMenuOptionIndex = $23                   ; $23

    CurrentLevelData_Actors_PointerLo = $3D     ; $3D
    InventoryBodyPartSelection = $4F            ; $4F
    CurrentLevelSceneNumber = $50               ; $50
	LevelData_MetaTiles_pointerLo = $63			; $63
	LevelData_CategoryThresholds_pointerLo = $6E	; $6E
	LevelData_Screens_pointerLo = $70			; $70
	LevelData_Stairs_pointerLo = $72			; $72
	DialogText_Ycoord = $77						; $77
	DialogText_Saved_ID = $79					; $79
    DialogTextID = $7F                          ; $7F
	CurrentDayBCD = $83							; $83
	
	Temp94 = $94								; $94

    SoundEffectRelatedPtrLo = $99               ; $99
    SoundEffectRelatedPtrHi = $9A               ; $9A

    Sound_StartSong_TrackDataPtr_Lo = $9D       ; $9D

    SoundTrackPtrLo = $A1                       ; $A1
    Sound_RecordPtrLo = $A3                     ; $A3
    Sound_TempPtrA7_lo = $A7                    ; $A7
    Sound_FadeCounter = $A9                     ; $A9
    Sound_FadeMode = $AA                        ; $AA

    Sound_SongPausedFlag_Channel0_square0 = $AB         ; $AB
    Sound_CurrentSongNumber_Channel0_square0 = $B1      ; $B1
    Sound_CurrentSongNumber_Channel2_triangle = $B3     ; $B3
    Sound_CUrrentSongNumber_Channel5_Percussion = $B6   ; $B6
	Sound_TrackDataPointer1Hi_Channel0_square0 = $BD	; $BD
    Sound_FlagsC3_Channel0_square0 = $C3                ; $C3
	
	Sound_LoopBeginPointerLo_Channel0_square0 = $E1	; $E1
	Sound_LoopBeginPointerHi_Channel0_square0 = $E7	; $E7
	
	Input_CurrentJoyButtonsOrig = $F1				; $F1
    Input_NewJoyButtonsWork = $F5                   ; $F5
    Input_CurrentJoyButtonsWork = $F7               ; $F7

    Sound_CacheAPUreg0and1_twonibbles = $0129       ; $0129
    Sound_EffectTableIndex = $0136                  ; $0136
    Sound_TabUnknown0138 = $0138                    ; $0138
    Sound_TabUnknown013A_squarewavesonly = $013A    ; $013A
    Sound_TabUnknown013C_squarewavesonly = $013C    ; $013C
    Sound_TabUnknown0140 = $0140                    ; $0140
    Sound_EffectTableResultHiNibble = $014C         ; $104C
    Sound_TabUnknown014E = $014E                    ; $014E
    Sound_EffectRelatedBytesRead = $0150            ; $0150
    Sound_TabUnknown0152 = $0152                    ; $0152
    Sound_TempPtr015C_lo = $015C                    ; $015C
    Sound_CurrentLogicalChannel = $0164             ; $0164
    Sound_PCMsampleActive = $016C                   ; $016C

    ObjectCurrentPose1 = $0300                  ; $0300

    ObjectScreenYCoord = $0324                  ; $0324
    ObjectScreenYCoordFrac = $0336              ; $0336
    ObjectScreenXCoordFrac = $035A              ; $035A
    ObjectYSpeed = $036C                        ; $036C
    ObjectXSpeed = $0390                        ; $0390

    ObjectType = $03B4                          ; $03B4
    ObjectCurrentActionType = $03D8             ; $03D8
    ObjectPoseChangeCounter = $03EA             ; $03EA
    ObjectCurrentPose2 = $03FC                  ; $03FC

    ObjectFacingLeft = $0420                    ; $0420

    ObjectAIvar1 = $0444                        ; $0444
    UnknownFlag0446 = $0446                     ; $0446
    ObjectAIvar2 = $0456                        ; $0456
    ObjectAIvar3 = $0468                        ; $0468
    Ending_PrimaryActionIndex = $047A           ; $047A
    ObjectAIvar4 = $048C                        ; $048C
    ObjectAIvar5 = $049E                        ; $049E
    ObjectAIvar6 = $04B0                        ; $04B0

    ObjectEnemyRemainingHP = $04C2              ; $04C2
    ObjectDialogTextIndex = $04D7               ; $04D7
	
	Unknown04ED_finalConfrontationRelated = $04ED	; $04ED

    APU_HW__4008_Reg0_channel2 = $4008          ; $4008
    APU_HW__4015_EnableChannelsMask = $4015     ; $4015