    MainMenuOptionIndex = $23                   ; $23

    SoundEffectRelatedPtrLo = $99               ; $99
    SoundEffectRelatedPtrHi = $9A               ; $9A

    SoundTrackPtrLo = $A1                       ; $A1

    Sound_FadeCounter = $A9                     ; $A9
    Sound_FadeMode = $AA                        ; $AA

    Sound_SongPausedFlag_Channel0_square0 = $AB         ; $AB
    Sound_CurrentSongNumber_Channel0_square0 = $B1      ; $B1
    Sound_CurrentSongNumber_Channel2_triangle = $B3     ; $B3
    Sound_CUrrentSongNumber_Channel5_Percussion = $B6   ; $B6
    Sound_FlagsC3_Channel0_square0 = $C3                ; $C3

    Sound_CacheAPUreg0and1_twonibbles = $0129       ; $0129
    Sound_EffectTableIndex = $0136                  ; $0136
    Sound_TabUnknown0138 = $0138                    ; $0138
    Sound_TabUnknown013A_squarewavesonly = $013A    ; $013A
    Sound_TabUnknown013C_squarewavesonly = $013C    ; $013C
    Sound_TabUnknown0140 = $0140                    ; $0140
    Sound_EffectTableResultHiNibble = $014C         ; $104C
    Sound_TabUnknown014E = $014E                    ; $014E
    Sound_EffectRelatedBytesRead = $0150            ; $0150
    Sound_TabUnknown0152 = $0152                    ; $0152
    Sound_TempPtr015C_lo = $015C                    ; $015C
    Sound_CurrentLogicalChannel = $0164             ; $0164
    Sound_PCMsampleActive = $016C                   ; $016C

    APU_HW__4008_Reg0_channel2 = $4008          ; $4008
    APU_HW__4015_EnableChannelsMask = $4015     ; $4015